MMCU=atmega168
MMCU2=atmega168
FREQ=16000000

all: main_test_serie.hex

main_test_serie.hex: main_test_serie.out
	avr-objcopy -O ihex -R .eeprom main_test_serie.out main_test_serie.hex

main_test_serie.out: main_test_serie.o usart.o
	avr-gcc -Wall -O2 -mmcu=$(MMCU) -DF_CPU=$(FREQ) main_test_serie.o usart.o -o main_test_serie.out

main_test_serie.o: main_test_serie.c
	avr-gcc -Wall -O2 -mmcu=$(MMCU) -DF_CPU=$(FREQ) main_test_serie.c -c

usart.o: ../common/usart.c
	avr-gcc -Wall -mmcu=$(MMCU) -DF_CPU=$(FREQ) ../common/usart.c -c


clean:
	rm *.o *.out *.hex *~

upload:
	sudo avrdude -c usbtiny -p $(MMCU2) -U flash:w:main_test_serie.hex